### ISSUE TITLE
Picking with block inside inventory will not switch to that block

### ISSUE THREAD

**Issue by Hollis131** [Sjouwer/pick-block-pro#21]
version 1.20.2
default settings

**Comment by Sjouwer** [comment]
I found this exact issue when I updated the mod to mc 1.20.4, which I fixed in release 1.7.23.
However, for mc 1.20.2 I never had this issue and I'm also unable to reproduce it.
Can you provide more information?

- which version of Pick Block Pro are you using?
- which version of Fabric API are you using?
- are you using Fabric or Quilt?
- do you experience this in singleplayer, multiplayer or both?

**Comment by Hollis131** [comment]
PBP 1.7.21, latest one for 1.20.2
fabricApi verson  0.91.3
using Fabric
Both

**Comment by Sjouwer** [comment]
I just tried it out with the exact same versions and didn't experience any issues.
Can you maybe explain a bit more what exactly you're doing?
Also, which other mods are you using? I suspect there might be a conflict with another mod

**Comment by Sjouwer** [comment]
Try out this version: https://modrinth.com/mod/pick-block-pro/version/1.7.27
I believe it should fix your issue, if however it doesn't then feel free to create a new issue with more information
